# Generated by Django 4.2.4 on 2023-08-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=10)),
                ("idno", models.CharField(max_length=20)),
                ("prnno", models.CharField(max_length=20)),
                (
                    "member_type",
                    models.CharField(
                        choices=[("teacher", "teacher"), ("student", "student")],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
