# Generated by Django 4.2.4 on 2023-08-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("isbnno", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technology", "technology"),
                            ("general", "general"),
                            ("programming", "programming"),
                            ("science", "science"),
                            ("novel", "novel"),
                        ],
                        max_length=50,
                    ),
                ),
                ("price", models.FloatField()),
                ("qty", models.IntegerField()),
            ],
        ),
    ]
