# Generated by Django 4.2.4 on 2023-08-07 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_loan"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("return_date", models.DateField()),
                ("charges", models.IntegerField()),
                (
                    "dateoverdue",
                    models.CharField(
                        choices=[("yes", "yes"), ("no", "no")], max_length=50
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.loan"
                    ),
                ),
            ],
        ),
    ]
